version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backend-analytics-init-db.sql:/docker-entrypoint-initdb.d/0_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: 
      always

  # pgadmin:
  #   depends_on:
  #     - postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
  #   ports:
  #     - "5050:80"
  #   restart: always

  backend_analytics:
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    build:
      context: ./backend-analytics
      dockerfile: Dockerfile
    ports:
      - 5223:5223
    environment:
      - ConnectionStrings__PostgreSQL=Server=host.docker.internal;Port=15432;Database=izumo_analytics;UserId=sa;Password=sa;
    restart: always

  collector_fake:
    depends_on:
      - backend_analytics
    build:
      context: ./collector-fake
      dockerfile: Dockerfile
    ports:
      - 5221:5221
    environment:
      - AnalyticsApi=http://host.docker.internal:5223/analytics/v1.0/
      - Generator__DelaySeconds=10
      - Generator__LatitudeMin=35344326
      - Generator__LatitudeMax=35401324
      - Generator__LongitudeMin=132685292
      - Generator__LongitudeMax=132911341
      - Generator__MaxBatchSize=30
      - Generator__MinBatchSize=10
    restart: always

  backend_admin:
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    build:
      context: ./backend-admin
      dockerfile: Dockerfile
    ports:
      - 5224:3000
    environment:
      - RAILS_ENV=production
      - H_IZUMO_NAVI_DATABASE_PASSWORD=${POSTGRES_USER}
      - H_IZUMO_NAVI_DATABASE_USERNAME=${POSTGRES_PW}
      - H_IZUMO_NAVI_DATABASE_PORT=15432
      - H_IZUMO_NAVI_DATABASE_HOST=host.docker.internal
      - SECRET_KEY_BASE=what-is-it
    command: >
        ash -c "rake db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"


  frontend_analytics:
    depends_on:
      - backend_analytics
    build:
      context: ./frontend-analytics
      dockerfile: Dockerfile
    environment:
      - "REACT_APP_API_ANALYTICS=${ANALYTICS_API}"
      - "REACT_APP_MAPBOX_API_KEY=${MAPBOX_API_KEY}"
    ports:
      - 8080:80
    restart: always